### ISSUE TITLE
Win32 Unable to find an entry point named 'WSASetService' in DLL 'ws2_32.dll'

### ISSUE THREAD

**Issue by JPhilC** [inthehand/32feet#122]
Hi Peter,

I have updated to v4.0.17 and it appears the changes made between v4.0.15 have broken the BluetoothListener code for Win32. The DoStart() method is failing with a "System.EntryPointNotFoundException".

Unable to find an entry point named 'WSASetService' in DLL 'ws2_32.dll'.

I'm wondering whether the changes to NativeMethods.cs may be the culprit.

Phil

**Comment by peterfoot** [comment]
Looks like combination of applying ExactSpelling=true to WSASetService and the actual entry point being WSASetServiceW. Will rebuild and release a new version.

**Comment by JPhilC** [comment]
I can confirm that this is now fixed.
