### ISSUE TITLE
The application is in break mode

### ISSUE THREAD

**Issue by orcunor** [inthehand/32feet#127]
I built the project and got this error:
![err](https://user-images.githubusercontent.com/52966278/119784447-e2115e80-bed6-11eb-9cce-99bef758be9e.PNG)

System.MissingMethodException: 'Method not found: 'Void InTheHand.Bluetooth.BluetoothDevice..ctor()'.'

**Comment by peterfoot** [comment]
.NET 5.0 (and 6.0) support is now added and will work as long as the consuming project is a Windows 10 target platform e.g. net5.0-windows10.0.19041.0 or later
