### ISSUE TITLE
What is the difference between WriteValueWithoutResponseAsync  and WriteValueWithResponseAsync ?

### ISSUE THREAD

**Issue by bbhxwl** [inthehand/32feet#146]
What is the difference between WriteValueWithoutResponseAsync  and WriteValueWithResponseAsync ?

I tried to send data with WriteValueWithResponseAsync today, but it didn't seem to work.

**Comment by peterfoot** [comment]
You need to check the Properties of a characteristic to see which method(s) it supports. A write without response is quicker because no acknowledgement is sent but this also means you won't know if an error occurred.
