### ISSUE TITLE
Can I support raspberry pie net core?

### ISSUE THREAD

**Issue by bbhxwl** [inthehand/32feet#149]
Can I support raspberry pie net core?

**Comment by behroozbc** [comment]
hi @peterfoot ,
Now can I use raspberry pie net core?

**Comment by bbhxwl** [comment]
> hi @peterfoot , Now can I use raspberry pie net core?

Not yet, c# there are few cross platform Bluetooth.

**Comment by peterfoot** [comment]
Closing this as Linux support is covered by issue #37
