### ISSUE TITLE
Multiple BluetoothService

### ISSUE THREAD

**Issue by kirax999** [inthehand/32feet#15]
hello, I'm looking for a way to put several Bluetooth Service on the same device example handsFree and phonebook

Do you have an idea ?

**Comment by peterfoot** [comment]
You can create multiple listening sockets with different service uuids. However we only support Rfcomm sockets so there isn't the capability built-in to support the audio stream of Handsfree service.

**Comment by tumelosbk** [comment]
Humble greetings.

A few years ago I built a c# app that copies the same file to multiple Bluetooth devices simultaneously using multi-threading. I am trying to recreate the same app, but with more features using newer technology(latest 32feet.net version and Visual Studio 2017)

I'm trying to recreate the project from scratch. But I keep getting an exception when I call "ObexWebResponse response = (ObexWebResponse)request.GetResponse();" that Only 1 use of the network/protocol/address can be used at a time.

So should I downgrade the library version? (If that's even possible) Or how can I get passed this issue?
Thanks for the help in advance
