### ISSUE TITLE
BluetoothGattCharacteristic have only 20 byte (default) for read

### ISSUE THREAD

**Issue by polipo** [inthehand/32feet#153]
Android for default have BluetoothGattCharacteristic set to 20 byte,
see https://stackoverflow.com/questions/24135682/android-sending-data-20-bytes-by-ble

For avoid this will be set the BluetoothGattService.RequestMtu(MYSIZE)

Question : 
How to set by InTheHand.BluetoothLE ?

Thanks

**Comment by peterfoot** [comment]
Currently this would only be possible in platform specific code - cast the GattService to Android.Bluetooth.BluetoothGattService and call RequestMtu. Looking at adding a method to get/set the MTU into the cross-platform API.

**Comment by polipo** [comment]
The Android have some problems to set a different value, it require to set twice my personal workaround is to set X-1 and then set X.

**Comment by peterfoot** [comment]
I found this in the WebBluetooth issues which details observations from different platforms - https://github.com/WebBluetoothCG/web-bluetooth/issues/284

**Comment by peterfoot** [comment]
In the latest release I've added a property to query the MTU value, also on Android it requests 512bytes and will negotiate a value with the remote device so it is more in the range of what you see with other platforms
