### ISSUE TITLE
Net 5 & Net 6 support

### ISSUE THREAD

**Issue by AndreGroeschel** [inthehand/32feet#154]
Hi there,

thx for the great library! We are evaluating it for a future project and are wondering if you plan to support Net 5 & 6 in the future.
Is this something you are planning to do?

Cheers,
André

**Comment by peterfoot** [comment]
Yes, it is being worked on, just working out some tools/build issues.

**Comment by AndreGroeschel** [comment]
Cool, very nice :)
Thank you!
