### ISSUE TITLE
Can't find the list of already paired devices

### ISSUE THREAD

**Issue by SjoCi** [inthehand/32feet#155]
In an older/different version of the InTheHand there was a IReadOnlyCollection<BluetoothDeviceInfo> PairedDevices property of the BluetoothClient class. That is no longer the case and I can't find it anywhere else.
Is this functionality still existing?

**Comment by peterfoot** [comment]
BluetoothClient has a PairedDevices property which is an IEnumerable<BluetoothDeviceInfo>

**Comment by SjoCi** [comment]
Sorry, it was my bad.
I was not aware that I used 32feet.NET - Legacy (v3.x) NuGet.
Thank you for the quick response.
