### ISSUE TITLE
Xamarin.iOS Bluetooth to W10 PC Support?

### ISSUE THREAD

**Issue by danielricci** [inthehand/32feet#157]
Hi.

I have a Xamarin app that has both an Android and iOS project (code is written in C#), and I'm able to use your library to communicate with my other C# application (through bluetooth) on my W10 PC when running your code on Android, but not on iOS. For example when I make a call to BluetoothClient.PairedDevices it returns values when running on Android, but on iOS its always empty.

Maybe i'm doing something wrong with the library, or maybe it's not supported?

**Comment by peterfoot** [comment]
The iOS part of the library is not fully implemented yet. iOS doesn't have a full API for Bluetooth Classic and so it uses the ExternalAccessory API which only supports certain device types which are MFI certified by Apple.

**Comment by danielricci** [comment]
Can I accomplish this using Bluetooth LE portion of your library?

**Comment by peterfoot** [comment]
Bluetooth LE is supported on iOS yes, but only the client side (consuming services/characteristics on another device) and not currently the server side (publishing services/characteristics).

**Comment by bbhxwl** [comment]
> Bluetooth LE is supported on iOS yes, but only the client side (consuming services/characteristics on another device) and not currently the server side (publishing services/characteristics).

I don't know why my IOS can't connect successfully. Can you give me some advice?

**Comment by danielricci** [comment]
Closing issue.
