### ISSUE TITLE
Android Gatt AutoConnect is always set to true

### ISSUE THREAD

**Issue by polipo** [inthehand/32feet#159]
The PlatformInit for Android, force the connection to autoconnect = true, this parameter is not always correct,
in my case I will control the disconnection and reconnection.

 private void PlatformInit()
        {
            _gattCallback = new GattCallback(this);
           _gatt = ((ABluetooth.BluetoothDevice)Device).ConnectGatt(Android.App.Application.Context, **true**, _gattCallback, ABluetooth.BluetoothTransports.Le);
        }

**Comment by peterfoot** [comment]
Thanks, good catch. Going forward I think the required behaviour is to set this false and allow the consumer of the library to manage reconnection, using events to detect a disconnection.

**Comment by polipo** [comment]
I have pulled a request for a change.
Thanks

**Comment by peterfoot** [comment]
Pull request #160 merged.
