### ISSUE TITLE
Pair and Remove pair locks up on RemovePairing

### ISSUE THREAD

**Issue by lattara** [inthehand/32feet#162]
During one execution of an app if you pair to a Bluethooth Device and then later on (without exiting the app) you Remove the BluetoothDevice, It will lockup the app.

We are a Windows Desktop application using .net4.7.2.
This was working in the 3.5 verion, but in 4.0.22 it hangs up

**Comment by peterfoot** [comment]
Callback issue fixed in 4.0.24
