### ISSUE TITLE
HFP receive audio

### ISSUE THREAD

**Issue by Salmondx** [inthehand/32feet#17]
I'm trying to implement a PC app that allows a user to answer a phone calls via PC. I've implemented a Bluetooth HFP profile (can dial a number, completed codec initiation phase, etc), but stuck on creating an audio channel. If I understand this specification correctly, HFP consists of 2 connections: control channel and audio channel.
How to connect to audio channel after codec negotiation phase using this library?

**Comment by Salmondx** [comment]
I think I should establish a SCO link, but I don't know how to do this. Do you have any ideas?

**Comment by peterfoot** [comment]
This is not something we plan to add as it's outside the scope of Rfcomm sockets.
