### ISSUE TITLE
Use of InTheHand.BluetoothLE with Xamarin Forms

### ISSUE THREAD

**Issue by arnulfrupp** [inthehand/32feet#170]
I'm trying the InTheHand.BluetoothLE nuget packet with Xamarin Forms.

To get familiar with it I tried Samples/BluetoothClientApp first.
I was able to compile and run it with UWP. Works fine.

Now when adding the nuget packet to my own app Bluetooth.GetAvailabilityAsync() never returns true.
I added the nuget packet to both the platform projects (starting with UWP) and the common (forms) project. 
The UWP project has Bluetooth capability activated in Package.appxmanifest.
Is this how the packet should be used. Any help is highly appreciated!

In 'MyMainPage_Appearing':

 while (!availability)
  {
      availability = await Bluetooth.GetAvailabilityAsync();
      await Task.Delay(500);
  }

--> Never stops

**Comment by sdmimaye** [comment]
Hi there. I am using this Library with Xamarin Forms. I would suggest you use the Xamarin.Essentials package. You can check the permission with:

var state = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();
if (state != PermissionStatus.Granted) {
    var change = await Permissions.RequestAsync<Permissions.LocationWhenInUse>();
    if (change != PermissionStatus.Granted) {
        throw new Exception("BLE permission denied...");
    }
}

Best regards
Michael

**Comment by bbhxwl** [comment]
> I'm trying the InTheHand.BluetoothLE nuget packet with Xamarin Forms.
> 
> To get familiar with it I tried Samples/BluetoothClientApp first. I was able to compile and run it with UWP. Works fine.
> 
> Now when adding the nuget packet to my own app Bluetooth.GetAvailabilityAsync() never returns true. I added the nuget packet to both the platform projects (starting with UWP) and the common (forms) project. The UWP project has Bluetooth capability activated in Package.appxmanifest. Is this how the packet should be used. Any help is highly appreciated!
> 
> In 'MyMainPage_Appearing':
> 
> while (!availability) { availability = await Bluetooth.GetAvailabilityAsync(); await Task.Delay(500); }
> 
> --> Never stops

I can't use the same problem as you. xamarin. forms android +ios
