### ISSUE TITLE
Could not load signature of InTheHand.Net.Bluetooth.Droid.AndroidNetworkStream:WriteAsync 

### ISSUE THREAD

**Issue by yss-sato** [inthehand/32feet#178]
Hi,
I'm using inthehand in .NET MAUI application to send data to Android device via Bluetooth, like this.

```
using BluetoothClient client = new BluetoothClient();
client.Connect(new BluetoothAddress(bd_addr), BluetoothService.SerialPort);
NetworkStream bt_stream = client.GetStream();
bt_stream.Write(data, 0, data.Length);
bt_stream.Close();
```

However, I faced an exception that is "Could not load signature of InTheHand.Net.Bluetooth.Droid.AndroidNetworkStream:WriteAsync" from GetStream method.
Since inthehand has been used for Xamarin and Android, I thought .NET MAUI is also supported.
Could you tell how to resolve this?

**Comment by peterfoot** [comment]
I think this may be because there is currently a monoandroid build of the library and a .NET 6 windows version but not a .NET 6 Android build. I will need to add this to the NuGet package.

**Comment by peterfoot** [comment]
This is resolved now with latest NuGet package.
