### ISSUE TITLE
System.ObjectDisposedException from BluetoothDevice.Finalize

### ISSUE THREAD

**Issue by r-pankevicius** [inthehand/32feet#179]
Package: InTheHand.BluetoothLE Version="4.0.22"
OS: Microsoft Windows [Version 10.0.19044.1586]

Just started to check if BluetoothLE may work for me.
I've created  .net 5 Windows console app, an async devices scanner that scans bluetooth devices around.

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.22" />
    <PackageReference Include="System.Runtime.InteropServices.WindowsRuntime" Version="4.3.0" />
  </ItemGroup>
</Project>
```
Program.cs:
```csharp
using InTheHand.Bluetooth;
using System;
using System.Threading.Tasks;

namespace InTheHand_BluetoothLE_Tests
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            Bluetooth.AdvertisementReceived += Bluetooth_AdvertisementReceived;
            BluetoothLEScan lescan = await Bluetooth.RequestLEScanAsync(new BluetoothLEScanOptions { AcceptAllAdvertisements = true });

            Console.ReadLine();

            lescan.Stop();
        }

        private static void Bluetooth_AdvertisementReceived(object sender, BluetoothAdvertisingEvent e)
        {
			Console.WriteLine($"Bluetooth_AdvertisementReceived: {e.Name}");
        }
    }
}
```
It works for some minutes writing out names of discovered devices. After some time it crashes:
```
Unhandled exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.TryAs[T](Guid iid, ObjectReference`1& objRef)
   at WinRT.IObjectReference.As[T](Guid iid)
   at WinRT.IObjectReference.As[T]()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at WinRT.SingleInterfaceOptimizedObject..ctor(Type type, IObjectReference objRef, Boolean requireQI)
   at Windows.Devices.Bluetooth.BluetoothLEDevice.Make__lazy_global__System_IDisposable()
   at Windows.Devices.Bluetooth.BluetoothLEDevice.Dispose()
   at InTheHand.Bluetooth.BluetoothDevice.DisposeAllNativeObjects()
   at InTheHand.Bluetooth.BluetoothDevice.Finalize()
```
Is this an issue in InTheHand.BluetoothLE or did I forget to dispose something?

**Comment by r-pankevicius** [comment]
Even in quite place, no devices detected I've ran into the same after some minutes:
```
InTheHand.BluetoothLE
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.TryAs[T](Guid iid, ObjectReference`1& objRef)
   at WinRT.IObjectReference.As[T](Guid iid)
   at WinRT.IObjectReference.As[T]()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at WinRT.SingleInterfaceOptimizedObject..ctor(Type type, IObjectReference objRef, Boolean requireQI)
   at WinRT.SingleInterfaceOptimizedObject..ctor(Type type, IObjectReference objRef)
   at Windows.Devices.Bluetooth.BluetoothLEDevice.Make__lazy_global__System_IDisposable()
   at Windows.Devices.Bluetooth.BluetoothLEDevice.AsInternal(InterfaceTag`1 _)
   at Windows.Devices.Bluetooth.BluetoothLEDevice.Dispose()
   at InTheHand.Bluetooth.BluetoothDevice.DisposeAllNativeObjects()
   at InTheHand.Bluetooth.BluetoothDevice.Finalize()
```

**Comment by peterfoot** [comment]
Seems to be thrown inside Windows.Devices.Bluetooth.BluetoothLEDevice.Dispose(). Possibly the object is being disposed more than once. Will investigate further.

**Comment by r-pankevicius** [comment]
Looks like this one:
https://github.com/MicrosoftDocs/windows-uwp/issues/498

**Comment by lewcianci** [comment]
Just hitting this now as well, but I could possibly submit a PR if I know where this problem lies?

**Comment by lewcianci** [comment]
Actually, I think this could be caused by this PR: https://github.com/inthehand/32feet/pull/133

Line 39 in BluetoothDevice.windows.cs has this in the *destructor* for the object:

```
 ~BluetoothDevice()
        {
            DisposeAllNativeObjects();
        }
```

Commenting out the destructor stopped this issue from happening. I'll see if this causes any other obvious issues...

**Comment by r-pankevicius** [comment]
@lewcianci 

> Commenting out the destructor stopped this issue from happening.

But it may lead to the memory leaks.

**Comment by peterfoot** [comment]
We can't remove this because it was necessary to support correct disconnection and free up the native objects. The issue is why a Dispose is getting called twice for a native object. The messy solution would be to wrap the Dispose call inside DisposeAllNativeObjects in a try/catch. It needs some additional logging so we can try and recreate and see which threads it is being called from.

**Comment by r-pankevicius** [comment]
Maybe some book keeping shall be done in `OnGattServerDisconnected()`? Now `BluetoothDevice` just informs subscribers by calling triggering event:
```csharp
        internal void OnGattServerDisconnected()
        {
            GattServerDisconnected?.Invoke(this, EventArgs.Empty);
        }

        /// <summary>
        /// Fired when an active GATT connection is lost.
        /// </summary>
        public event EventHandler GattServerDisconnected;
```

**Comment by r-pankevicius** [comment]
@lewcianci This is what @peterfoot said and he called it a _messy solution_ (I agree):

> The messy solution would be to wrap the Dispose call inside DisposeAllNativeObjects in a try/catch.

**Comment by los93sol** [comment]
I am currently experiencing the same thing.  In my case I maintain a list of the advertisements to display in a UI.  

I found that if I always append to the list indefinitely, things are fine (obviously since the destructor never gets called).
If I update previously seen advertisements in the list by replacing them then the issue occurs.
If I do absolutely nothing with the items the issue occurs as well which makes sense because the destructor would be getting called.

This seems like what's happening is we have multiple instances of BluetoothAdvertisementEvent, each with their own BluetoothDevice, but I believe each of those instances are referencing the same instance of BluetoothLEDevice so the first one gets disposed and disposes BluetoothLEDevice in all instances of BluetoothAdvertisementEvent.  This seems extremely problematic since you may be using the BluetoothAdvertisementEvent that has not yet been disposed so I agree that a simple try/catch is not the correct solution here.

@peterfoot Can you confirm if I'm on the right track with my thinking?  If so, any ideas on how to resolve it?

**Comment by los93sol** [comment]
Did a little test and called BluetoothLEDevice.FromBluetoothAddressAsync(args.BluetoothAddress, args.BluetoothAddressType); multiple times to get multiple instances and Disposed one of them and the others stayed intact so it doesn't look like this is what's happening after all

**Comment by los93sol** [comment]
I also threw a counter in DisposeAllNativeObjects and it appears it's only being called once prior to the exception being thrown, kind of out of ideas on this one, it's starting to seem more and more like the OS has actually disposed it out from underneath us for some reason

**Comment by los93sol** [comment]
This definitely looks to be related to the use of the destructor.  To test I used the following...

public class Test
{
    private readonly BluetoothLEDevice _device;

    public Test(ulong bluetoothAddress)
    {
        IAsyncOperation<BluetoothLEDevice> deviceAsync = BluetoothLEDevice.FromBluetoothAddressAsync(247023104633615);

        // https://github.com/inthehand/32feet/issues/96
        // Wait some time for this task to complete otherwise the event will fire
        // before the 'Device' property as been set.
        if (deviceAsync.AsTask().Wait(7000))
        {
            _device = deviceAsync.GetResults();
        }
        else
        {
            try
            {
                // The documents state that it is not possible to cancel 'FromBluetoothAddressAsync'
                // so mask any exceptions before calling this.
                deviceAsync.Cancel();
            }
            catch
            {
            }
        }
    }

    ~Test()
    {
        _device.Dispose();
    }
}

and invoked it with....

var address = {whatever device address you have}

for (var i = 0; i < 500; i++)
{
                var x = new Test(address);
}

That seems to be enough to repro it and isolate it from being impacted by any other code

**Comment by los93sol** [comment]
Even more interesting....the following works fine, note, I even kicked it all the way up to 2k instances and it does not throw

public class Test2 : IDisposable
{
    private readonly BluetoothLEDevice _device;

    public Test2(ulong bluetoothAddress)
    {
        IAsyncOperation<BluetoothLEDevice> deviceAsync = BluetoothLEDevice.FromBluetoothAddressAsync(247023104633615);

        // https://github.com/inthehand/32feet/issues/96
        // Wait some time for this task to complete otherwise the event will fire
        // before the 'Device' property as been set.
        if (deviceAsync.AsTask().Wait(7000))
        {
            _device = deviceAsync.GetResults();
        }
        else
        {
            try
            {
                // The documents state that it is not possible to cancel 'FromBluetoothAddressAsync'
                // so mask any exceptions before calling this.
                deviceAsync.Cancel();
            }
            catch
            {
            }
        }
    }

    public void Dispose()
    {
        _device.Dispose();
    }
}

            var items = new List<Test2>();
            var address = {whatever device address you have}

            for (var i = 0; i < 2000; i++)
            {
                items.Add(new Test2(address));
            }

            foreach (var item in items)
            {
                item.Dispose();
            }
