### ISSUE TITLE
await WriteAsync seems to return before all the data is actually written to the stream

### ISSUE THREAD

**Issue by snydesc** [inthehand/32feet#217]
I noticed that on Android (Xamarin Android Project targeting Android 12.0) that when calling await WriteAsync the call returns before all the data is written to the stream.

The following code is used to send data to a printer.
If I don't include the delay and just close the stream then the data never prints.
If the number of bytes I'm trying to pass to WriteAsync is large then a larger delay is needed.

I would expect awaiting the call would wait until all data is written, but that does not seem to be the case. 

```
byte[] bytes = System.Text.Encoding.UTF8.GetBytes(cmd); 
using (var bs = client.GetStream())
{
   await bs.WriteAsync(bytes, 0, bytes.Length);
   await Task.Delay(250); // Delay is needed otherwise stream closes before data is written.
   bs.Close();
}
```

**Comment by peterfoot** [comment]
Android uses a buffered stream underneath the hood so the method returns when it has finished writing to the buffer. You can force it to flush the buffer and write all to the device using Flush or FlushAsync on the stream.
