### ISSUE TITLE
NullReferenceException in Android

### ISSUE THREAD

**Issue by kalpasrl** [inthehand/32feet#221]
Hi,
in class DevicePickerReceiver there is a NullReferenceException where no device is chosen, after Bluetooth scan.

To fix it, you need to check if Extras is null.

From:
var dev = (Android.Bluetooth.BluetoothDevice)intent.Extras.Get("android.bluetooth.device.extra.DEVICE");

To:
var dev = (Android.Bluetooth.BluetoothDevice)intent.Extras?.Get("android.bluetooth.device.extra.DEVICE");

Thank you
Stefano

**Comment by peterfoot** [comment]
Resolved in 4.0.31. Thanks for reporting!
