### ISSUE TITLE
Same problem 

### ISSUE THREAD

**Issue by rswethashankar92** [inthehand/32feet#223]
When i try to connect using IntheHand.net.bluetooth Bluetoothclient. I get an exception.
`client.BeginConnect(endPoint, new AsyncCallback(ConnectCB), client)
`
I get null reference exception.

What might be causing the exception?

_Originally posted by @AsfandNadeem in https://github.com/inthehand/32feet/issues/51#issuecomment-908246550_

**Comment by peterfoot** [comment]
Closing as duplicate of #51
