### ISSUE TITLE
Why does BluetoothListener.AcceptBluetoothClient not wait?

### ISSUE THREAD

**Issue by NilsHoyer** [inthehand/32feet#225]
I would like to listen to the serial port of the Bluetooth adapter on a Windows device.

First, I start a separate `Task` for the listener in the main thread:

    BluetoothListener _bluetoothListener;
    Task? _bluetoothListenerTask;

    ...

    _bluetoothListener = new (BluetoothService.SerialPort);
    _bluetoothListener.Start();

    _bluetoothListenerTask = new(new(BluetoothListenerTask));
    _bluetoothListenerTask.Start();

This starts a new Task, listening for new connections of remote devices and start a second new Task to handle that conntion:

    private void BluetoothListenerTask()
    {
        while (_bluetoothListener.Active)
        {
           var client = _bluetoothListener.AcceptBluetoothClient();
           Task bluetoothProcessorTask = new(new(BluetoothProcessorTask), client);
           bluetoothProcessorTask.Start();
        }
    }

    private async void BluetoothProcessorTask(object? state)
    {
        ...
    }

Unfortunately, `BluetoothListener.AcceptBluetoothClient` does not wait for incoming connections. It just gives a `null` value instead of a `BluetoothClient` object back.

Because of this, my `BluetoothListenerTask` tasks runs the whole time and costs a lot of resources.

How can I **wait** for incoming connections?

**Comment by peterfoot** [comment]
What platform are you running this on? Only the Windows platform has an implementation for BluetoothListener and there is a bug in the Android code where it doesn't throw a PlatformNotSupportedException when you call start.

**Comment by peterfoot** [comment]
Is there any debug window output which might indicate an error at the underlying Socket level? What windows platform are you building for? Only the Win32 builds support BluetoothListener currently.

**Comment by NilsHoyer** [comment]
I'm developing in the VS 2022 IDE. I can't see any further hint.

I've downloaded your code (via GIT) and tried to use it without the NuGet package. But I'm too stupid to execute it. So I don't have an idea, how I can assist you with more details.

**Comment by NilsHoyer** [comment]
Do you plan to offer the BluetoothListener for Android too?

**Comment by NilsHoyer** [comment]
.Net has a good [library for Bluetooth](https://learn.microsoft.com/en-us/dotnet/api/android.bluetooth.bluetoothserversocket?view=xamarin-android-sdk-12) a Android with Bluetooth listening. Why don't you implement it?

**Comment by NilsHoyer** [comment]
I can get incoming Bluetooth connections via your `BluetoothListener.AcceptBluetoothClient()` right now.

But not via .Net `StreamSocketListener.BindServiceNameAsync` with the followin code:

    listener = new StreamSocketListener();
    listener.ConnectionReceived += BtConnection_ReceivedEvent;

    await listener.BindServiceNameAsync(rfcommProvider.ServiceId.AsString(), SocketProtectionLevel.BluetoothEncryptionAllowNullAuthentication);

    string SdpServiceName = Config.AppName;
    const byte SdpServiceNameAttributeType = (4 << 3) | 5;
    const UInt16 SdpServiceNameAttributeId = 0x100;

    // Set the SDP attributes and start Bluetooth advertising
    DataWriter sdpWriter = new DataWriter();

    // Write the Service Name Attribute.
    sdpWriter.WriteByte(SdpServiceNameAttributeType);

    // The length of the UTF-8 encoded Service Name SDP Attribute.
    sdpWriter.WriteByte((byte)SdpServiceName.Length);

    // The UTF-8 encoded Service Name value.
    sdpWriter.UnicodeEncoding = Windows.Storage.Streams.UnicodeEncoding.Utf8;
    sdpWriter.WriteString(SdpServiceName);

    // Set the SDP Attribute on the RFCOMM Service Provider.
    if (rfcommProvider.SdpRawAttributes.ContainsKey(SdpServiceNameAttributeId))
        rfcommProvider.SdpRawAttributes.Remove(SdpServiceNameAttributeId);
    rfcommProvider.SdpRawAttributes.Add(SdpServiceNameAttributeId, sdpWriter.DetachBuffer());

    // Start Bluetooth advertising
    rfcommProvider.StartAdvertising(listener);

Do you have an idea, how this fails?

**Comment by peterfoot** [comment]
Added WinRT and Android handlers in 4.0.31
