### ISSUE TITLE
Investigate pairing problems on Windows 10

### ISSUE THREAD

**Issue by peterfoot** [inthehand/32feet#23]
PairRequest doesn't appear to be working successfully and OS will pop up a notification that connection failed. It appears that calling SetPin first is successful so that may be a workaround before a fix can be applied.

**Comment by wangpeibin** [comment]
When will the bug be fixed?

**Comment by skytrace2016** [comment]
Hello,I have also met this problem when my windows 10 finished version 1803 update.And my other laptop which is not updated to latest version is still run normally.So please help fixing this bug ASAP,thank you so much.
