### ISSUE TITLE
Unable to find dependencies for InTheHand.BluetoothLE.dll

### ISSUE THREAD

**Issue by scottdmorgan** [inthehand/32feet#233]
When my Visual C# setup project is doing its pre-build validation I am getting these warnings:
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.WINDOWSRUNTIME' (Signature='B77A5C561934E089' Version='4.0.14.0') of assembly 'InTheHand.BluetoothLE.dll'
WARNING: Unable to find dependency 'WINDOWS.FOUNDATION.FOUNDATIONCONTRACT' (Signature='(null)' Version='4.0.0.0') of assembly 'InTheHand.BluetoothLE.dll'
WARNING: Unable to find dependency 'WINDOWS.FOUNDATION.UNIVERSALAPICONTRACT' (Signature='(null)' Version='15.0.0.0') of assembly 'InTheHand.BluetoothLE.dll'

I see that I have these packages installed along with many others:
InTheHand.BluetoothLE v4.0.25
System.Runtime.WindowsRuntime v4.6.0

Does anyone know the significance of these warnings? I haven't seen any runtime problems with the InTheHand.BluetoothLE.dll on the Windows PCs where I have installed my application.

**Comment by peterfoot** [comment]
What .NET platform does your project target? e.g. .NET Framework 4.x, .NET 5.0x etc This will determine which .dll is used and the dependencies are different because there are changes in the way interop with the Windows/UWP APIs works.

**Comment by scottdmorgan** [comment]
currently .NET Framework 4.7.2

**Comment by scottdmorgan** [comment]
Here's my packages.config:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="InTheHand.BluetoothLE" version="4.0.25" targetFramework="net472" />
  <package id="Microsoft.Bcl.HashCode" version="1.1.1" targetFramework="net472" />
  <package id="Microsoft.CSharp" version="4.7.0" targetFramework="net472" />
  <package id="Microsoft.Windows.SDK.Contracts" version="10.0.22621.2" targetFramework="net472" />
  <package id="Serilog" version="2.11.0" targetFramework="net472" />
  <package id="Serilog.Sinks.Console" version="4.0.1" targetFramework="net472" />
  <package id="Serilog.Sinks.File" version="5.0.0" targetFramework="net472" />
  <package id="Stub.System.Data.SQLite.Core.NetFramework" version="1.0.116.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net472" />
  <package id="System.CodeDom" version="6.0.0" targetFramework="net472" />
  <package id="System.Data.SQLite.Core" version="1.0.116.0" targetFramework="net472" />
  <package id="System.Management" version="6.0.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.5" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net472" />
  <package id="System.Runtime.InteropServices.WindowsRuntime" version="4.3.0" targetFramework="net472" />
  <package id="System.Runtime.WindowsRuntime" version="4.6.0" targetFramework="net472" />
  <package id="System.Runtime.WindowsRuntime.UI.Xaml" version="4.6.0" targetFramework="net472" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net472" />
</packages>

**Comment by scottdmorgan** [comment]
When I install InTheHand.BluetoothLE.4.0.25 with NuGet I see this:

Attempting to gather dependency information for package 'InTheHand.BluetoothLE.4.0.25' with respect to project 'DriScope', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 97 ms
Attempting to resolve dependencies for package 'InTheHand.BluetoothLE.4.0.25' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'InTheHand.BluetoothLE.4.0.25'
Resolved actions to install package 'InTheHand.BluetoothLE.4.0.25'
Adding package 'Microsoft.Windows.SDK.Contracts.10.0.22621.2' to folder 'C:\SVN\SDAC2\APP\trunk\packages'
Added package 'Microsoft.Windows.SDK.Contracts.10.0.22621.2' to folder 'C:\SVN\SDAC2\APP\trunk\packages'
Added package 'Microsoft.Windows.SDK.Contracts.10.0.22621.2' to 'packages.config'
Successfully installed 'Microsoft.Windows.SDK.Contracts 10.0.22621.2' to DriScope
Adding package 'InTheHand.BluetoothLE.4.0.25' to folder 'C:\SVN\SDAC2\APP\trunk\packages'
Added package 'InTheHand.BluetoothLE.4.0.25' to folder 'C:\SVN\SDAC2\APP\trunk\packages'
Added package 'InTheHand.BluetoothLE.4.0.25' to 'packages.config'
Successfully installed 'InTheHand.BluetoothLE 4.0.25' to DriScope
Executing nuget actions took 2.23 sec
Time Elapsed: 00:00:02.7741800
========== Finished ==========

**Comment by peterfoot** [comment]
I'm hoping this warning won't actually mean there is a problem. The only thing I can see is that the net461 version of the dll (which net472 will use) specifies the target platform version as 10.0.19041.0 but references the interop library Microsoft.Windows.SDK.Contracts 10.0.22621.2 and it should probably be updated so that these match. Either way the minimum supported version is 10.0.17763, if your project targets an older version of Windows that might cause a warning and the code would fail.

**Comment by scottdmorgan** [comment]
I haven't seen any problems but I just wanted to make sure there won't be issues when my software is used on some user's Windows PCs.
I see you have bumped Microsoft.Windows.SDK.Contracts from 10.0.22621.2 to 10.0.22621.755 which is the latest version. Will you be releasing a new InTheHand.BluetoothLE soon? I have pulled your latest code but I'm not sure how to build it myself.

**Comment by scottdmorgan** [comment]
I performed these updates today using NuGet:
InTheHand.BluetoothLE.4.0.25 -> InTheHand.BluetoothLE.4.0.26
Microsoft.Windows.SDK.Contracts.10.0.22621.2 -> Microsoft.Windows.SDK.Contracts.10.0.22621.755

After doing this I get this error:
1>C:\SVN\SDAC2\APP\trunk\packages\Microsoft.Windows.SDK.Contracts.10.0.22621.755\build\Microsoft.Windows.SDK.Contracts.targets(4,5): error : Must use PackageReference

Do I need to right-click on my packages.config and select "Migrate packages.config to PackageReference..."? After I do that I have a slew of other errors that appear.

https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

Is Microsoft forcing me to migrate from packages.config to PackageReference or is there a way around this?

**Comment by scottdmorgan** [comment]
Microsoft solved my issue:

In general, setup projects don’t understand WinMDs.  This package is a bit of a special case in that it’s used by .NET Framework projects and contains WinMD files, which is not common (though I know it’s supported, as described [here](https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3135560e-454455535732-4ae20a122df82141&q=1&e=f8b53353-ee69-4d8f-a172-ba7ffafba1c6&u=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows%2Fapps%2Fdesktop%2Fmodernize%2Fdesktop-to-uwp-enhance)).  You can likely get the behavior you’re looking for by excluding all these winmds from the setup project.  Expand “Dependencies”, multi-select all the WinMDs, then right click and Exclude.  This will of course exclude them from your installer, which is fine since they’re just metadata files used at build time.

I am still having this exception issue but it's separate to I will close this issue.
