### ISSUE TITLE
Gatt.GetPrimaryServiceAsync(..) not working on iOS

### ISSUE THREAD

**Issue by arnulfrupp** [inthehand/32feet#237]
Platform: net6.0-ios
Lib: InTheHand.BluetoothLE 4.0.25

**Get Primary Service:**

> GattService primaryService;
> Guid serviceGuid = Guid.Parse("..myGuid..");
> 
> await bleDevice.Gatt.ConnectAsync();
> primaryService = await bleDevice.Gatt.GetPrimaryServiceAsync(serviceGuid);

<br>
The code above does not deliver the expected service on iOS. It does work on windows.
I tracked it down to '32feet\InTheHand.BluetoothLE\Platforms\Apple\BluetoothUuid.unified.cs':<br>
<br>

**Line 38 and below:**

>  default:
>  b[0] = uuid.Data[3];
>  b[1] = uuid.Data[2];
>  b[2] = uuid.Data[1];
>  b[3] = uuid.Data[0];
>  b[4] = uuid.Data[5];
>  b[5] = uuid.Data[4];
>  b[6] = uuid.Data[7];
>  b[7] = uuid.Data[6];
>  Marshal.Copy(uuid.Data.Bytes, b, 8, 8);

<br>
I belive it should say:

> Marshal.Copy(uuid.Data.Bytes + 8, b, 8, 8);

Otherwise the first 8 bytes are copied into the second 8 bytes again. Parameter 'startIndex' is for destination only.
With that change, everything is working as expected.

**Copy(IntPtr, Byte[], Int32, Int32)**

> public static void Copy (IntPtr source, byte[] destination, int startIndex, int length);
> **startIndex**  Int32
> The zero-based index in the **destination** array where copying should start

<br>
Would be great if that could be fixed in a next release.

**Comment by peterfoot** [comment]
Thanks, the fix is in 4.0.26 which should be on NuGet shortly.
