### ISSUE TITLE
Fix code blocks in Wiki

### ISSUE THREAD

**Issue by kenger** [inthehand/32feet#25]
Hi,

almost all the code examples in the wiki are in the wrong format. Can someone fix them?

Some example are the OBEX page and all its subpages.

**Comment by peterfoot** [comment]
The wiki was imported from codeplex and their markdown is slightly different. requires the {code} tags to be replaced with 
\```vbnet or \```csharp tags and the closing tags replaced with
\```

**Comment by peterfoot** [comment]
I'm going to go ahead and close this now, please re-open if there are specific pages which still have issues.
