### ISSUE TITLE
Bluetooth.RequestDeviceAsync fails in BluetoothBLE in iOS Maui

### ISSUE THREAD

**Issue by mdima** [inthehand/32feet#262]
If I call the instruction: 

`currentDevice = await Bluetooth.RequestDeviceAsync(options); `

I receive as error: 

**Message:**
 	System.ArgumentException: 'idx'

**Call stack:** 
 	0x10 in Foundation.NSData.get_Item	C#
 	0x93 in InTheHand.Bluetooth.BluetoothUuid.op_Implicit	C#
 	0xCF in InTheHand.Bluetooth.BluetoothAdvertisingEvent..ctor	C#
 	0x21 in InTheHand.Bluetooth.Bluetooth.OnDiscoveredPeripheral	C#
 	0x5 in InTheHand.Bluetooth.Bluetooth.BluetoothDelegate.DiscoveredPeripheral	C#

The package I use is: InTheHand.BluetoothLE, version 4.0.27. 
The project targets net6.0-ios

Is necessary some other details? 

Thanks,
Michele

**Comment by peterfoot** [comment]
I'm afraid I haven't been able to debug this yet as my development environment is broken for .NET MAUI. However I was able to verify the crash. The same code in the latest Xamarin dll is working correctly though.I'll post another update once I've been able to step into the code and investigate properly.

**Comment by mdima** [comment]
Thanks @peterfoot !

**Comment by peterfoot** [comment]
I've made some changes in the source code which should have this up and running again. I've only tested on .NET 6 so far, not .NET 7 and it's not built into a NuGet yet...

**Comment by mdima** [comment]
Thank you @peterfoot ! I will update the package as soon as it will be available on NuGet. Also, for me .NET 6 is perfect...

**Comment by mdima** [comment]
Ok, I got the problem. 
Happens when the library finds some device with a null name. :S

**Comment by peterfoot** [comment]
Okay, I'll check this out because if it's unable to determine a name it should have a backup identifier.

**Comment by mdima** [comment]
Thanks! :)

**Comment by peterfoot** [comment]
Fixed - picker now displays identifier if name is null
