### ISSUE TITLE
Which version of Bluetooth classic?

### ISSUE THREAD

**Issue by fgroupindonesia** [inthehand/32feet#263]
![image](https://user-images.githubusercontent.com/7123388/215450206-b75b3e12-240a-404c-95c3-9a684471184e.png)

Does it means :
- Bluetooth 2.0 and below?
- and no way to access Bluetooth 4.0?

I'm currently need of Bluetooth 3 or 4.0 capability if possible in my .NET 4.5 projects....

**Comment by peterfoot** [comment]
The InTheHand.Net.Bluetooth library supports Bluetooth Classic  (RFComm) services for all versions of Bluetooth.

InTheHand.BluetoothLE supports Bluetooth Low Energy (GATT) services and has different requirements.
