### ISSUE TITLE
Reading and writing to BLE Characteristics through Unity

### ISSUE THREAD

**Issue by LloydMcInnes** [inthehand/32feet#27]
Hi Peter,

I'm working with some Bluetooth Low Energy ESP32 boards and trying to access them through Unity.
I saw a sample of code that you made to show printing from RfcommService from within Unity: https://gist.github.com/peterfoot/ea07a026a6c9d978fd0f27c2431bc745

Was hoping for something similar for Bluetooth Low Energy. The current sample only shows paired devices.
Have been using this Microsoft BLE Explorer UWP app for testing (https://github.com/Microsoft/BluetoothLEExplorer), but we need to be able to read and write the services and characteristics within Unity.

These are some samples of the kind of code running on the boards:
https://github.com/nkolban/ESP32_BLE_Arduino/blob/master/examples/BLE_uart/BLE_uart.ino

Any help with this would be greatly appreciated.

Thanks,
Lloyd McInnes

**Comment by peterfoot** [comment]
I’m currently working on BTLE support but it’s not integrated yet

**Comment by peterfoot** [comment]
Please try the InTheHand.BluetoothLE library. It includes a .NET Framework version which should work under Mono inside Unity (Windows 10 only). I'm working on adding a .NET Core version to the package too for other desktop apps.
