### ISSUE TITLE
WPF +DotNet6

### ISSUE THREAD

**Issue by wagenheimer** [inthehand/32feet#288]
Is WPF with Dot Net 6 already compatible?

Bluetooth.GetAvailabilityAsync() is always returning null for me.

Does it already work or I need to back to Dot Net 4.8?

**Comment by wagenheimer** [comment]
I will need to use the project on Windows 7. Will it work, which configuration should I use?

**Comment by peterfoot** [comment]
.NET 6.0 is supported but Windows 10 is required - Windows 7 doesn't have the underlying Bluetooth LE support.

**Comment by wagenheimer** [comment]
Thanks for the answer! So there is no way to support BluetoothLE on Windows 7?

Do you have any idea why Bluetooth.GetAvailabilityAsync() is always returning false for me?

I tried to download the source code and then create a new Dotnet6 subproject to be able to debug, but then I can't run it."

"InTheHand.BluetoothLE.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  An updated version of the component supporting .NET 5 is needed."


"InTheHand.BluetoothLE.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher. An updated version of the component supporting .NET 5 is needed.

**Comment by wagenheimer** [comment]
I managed to make it work with DotNet 6 by changing the TargetOSVersion to 10.0.19041.0. 

However, I'm not sure if using .NET 4.8 also requires a minimum version of 10.0.19041.0 for BluetoothLE to function properly. Can you confirm this?

**Comment by peterfoot** [comment]
The dll is built against the 10.0.19041 SDK so you must target that or higher, however it will run on 10.0.17763.0 and later.
