### ISSUE TITLE
Can't disconnect a bluetooth connection

### ISSUE THREAD

**Issue by hchtao** [inthehand/32feet#30]
Hi,
   I am using 32feet in Windows. I use BluetoothClient.close to disconnect from a device, but it has no effect.
   My code is like following, hope to get your answer.

BluetoothClient client = new BluetoothClient();
void Connect()
{
     BluetoothEndPoint ep = new BluetoothEndPoint(device.DeviceAddress, BluetoothService.Handsfree);
     client.Connect(ep);
     //check connection
}
void Disconnect()
{
     client.Close();
     client.Dispose();
}

**Comment by peterfoot** [comment]
Looking into this Close and Dispose both do the same thing so you only need to call one. Is Connected still showing true after Dispose?

**Comment by hchtao** [comment]
Connected is false after dispose, but in the bluetooth page of the Windows, my device is still connected

**Comment by peterfoot** [comment]
I notice you are calling the Handsfree service - is Windows or another app using the device for audio?

**Comment by hchtao** [comment]
My device is a BeatsX earphone. I tried to use SerialPort and AudioSink, still not work.

**Comment by hchtao** [comment]
I add callback 
BluetoothWin32Events myEvent = new BluetoothWin32Events();
myEvent.InRange += new EventHandler<BluetoothWin32RadioInRangeEventArgs>(HandleTest);

but HandleTest has not receive disconnect event.
Connected of bluetoothclient is false, but the connected of BluetoothDeviceInfo is still true.
