### ISSUE TITLE
BluetoothDeviceInfo.ClassOfDevice.Device returns unknown (7936) When running in Android < 12

### ISSUE THREAD

**Issue by euquiq** [inthehand/32feet#303]
Hi there!
Same code, running in an Android 12.1 device, returns the correct device class. 

`
        BluetoothDeviceInfo keyb = null;
        var picker = new BluetoothDevicePicker();
        keyb = await picker.PickSingleDeviceAsync();

        string Name = "";
        string Address = "";

        //Device has been chosen and it is keyboard-like
        if (keyb != null)
        {
               if (keyb.ClassOfDevice.Device == DeviceClass.PeripheralKeyboard)
               {
                    _Name = keyb.DeviceName;
                    Address = keyb.DeviceAddress.ToString());
               }
               else
               {
                    _Name = "NOT A KEYBOARD";
                    Address = "NOT A KEYBOARD";
               }
        } `
        
        Same code, same bluetooth keyboard, is correctly identified when this runs on Android 12.1, but throws "NOT A KEYBOARD" if run on a lesser SDK (i.e. Android 10)

**Comment by peterfoot** [comment]
This looks like the version where Android permissions changed - check that you have both the "new" and older permissions in your manifest:-
https://github.com/inthehand/32feet/wiki/Permissions
