### ISSUE TITLE
Does InTheHand have Bluetooth Classic support for iOS?

### ISSUE THREAD

**Issue by rimex-bkimmett** [inthehand/32feet#320]
I am writing an app in .NET MAUI, and I saw a comment suggesting that InTheHand might offer Bluetooth Classic support on iOS. (i.e. connect to arbitrary BT devices, not just mFi devices). Does/will it?

**Comment by peterfoot** [comment]
No, it can only use MFi devices. There isn't an underlying API to support other Bluetooth Classic devices and it's unlikely Apple will add it in the future.

**Comment by rimex-bkimmett** [comment]
Oh, that's a pity. Thank you for letting me know, though.
