### ISSUE TITLE
Bluetooth.ScanForDevicesAsync() return a list of null objects

### ISSUE THREAD

**Issue by digitalfr4nk** [inthehand/32feet#333]
Hi,

I have been trying to get a list of BLE devices, and using a few of your examples it seems I am stuck in a couple of places:

1. Both Bluetooth.ScanForDevicesAsync() and Bluetooth.GetPairedDevicesAsync() return correct number of items but they're all null!
2. BluetoothDevice device = await Bluetooth.RequestDeviceAsync(options); after selecting a device from the poopup, it returns null. (again this is from the example.)

![image](https://github.com/inthehand/32feet/assets/79330257/7fe12a63-1312-490b-94e3-250e6b1e116f)

Any ideas? (I am using a UWP app, Win11, VS2022)

**Comment by digitalfr4nk** [comment]
I got it figured out, and I'll leave this here in case it helps any one else: 
I neglected to include `<DeviceCapability Name="bluetooth"/>` in the Package.appxmanifest.

**Comment by peterfoot** [comment]
Glad you discovered the issue. However this shouldn't have happened because the behaviour is not clear. I will look at changing it to throw a descriptive exception when it fails with missing permission.
