### ISSUE TITLE
Does not run with Native AOT

### ISSUE THREAD

**Issue by denys-volodarskyi** [inthehand/32feet#352]
There seems to be some reflection issue to run project with PublishAot enabled. 

Throws exception on
```csharp
await Bluetooth.RequestDeviceAsync()
```

**Comment by peterfoot** [comment]
Can you provide more information on platform, version, your Linker/Trimming options etc

**Comment by denys-volodarskyi** [comment]
It's Windows with DotNet Preview. Maybe it's actually AOT compiler issue.

I've created test application:
https://github.com/denys-volodarskyi/Test_BLE_GUI

**Comment by denys-volodarskyi** [comment]
Seems problem is Windows APP SDK does not support NativeAOT yet.
https://github.com/dotnet/maui/issues/17713
