### ISSUE TITLE
BluetoothDeviceInfo from partial class to abstract

### ISSUE THREAD

**Issue by polipo** [inthehand/32feet#359]
In last commit of Bluetooth, there's change from partial class to abstract,
and I cannot resolve how to create an instance of BluetoothDeviceInfo
from macAddress.

Please, can help and explain how to do it? 

 deviceInfo = new BluetoothDeviceInfo(new InTheHand.Net.BluetoothAddress(ulong.Parse(Encoding.ASCII.GetString(_macAddress), System.Globalization.NumberStyles.HexNumber, System.Globalization.CultureInfo.InvariantCulture)));

Thanks

**Comment by peterfoot** [comment]
Sorry, looks like this was a knock-on effect of changing the implementation to support multiple platform variants of BluetoothDeviceInfo. I think the solution is a single public class which then holds the platform specific instance internally, similar to how the BluetoothClient etc are implemented.

**Comment by polipo** [comment]
Hi, have you a pratical solution or workaround for the last release 4.1.40?

Because i use to create a BluetoothClient by its macaddress like source above:

    _connection = new BluetoothClient();

    deviceInfo = new BluetoothDeviceInfo(new InTheHand.Net.BluetoothAddress(ulong.Parse(Encoding.ASCII.GetString(_macAddress), System.Globalization.NumberStyles.HexNumber, System.Globalization.CultureInfo.InvariantCulture)));

    if (deviceInfo == null)
    {
        { throw new ApplicationException("Device not paired"); }
    }
......

**Comment by peterfoot** [comment]
Fixed in 4.1.42

**Comment by dilbie** [comment]
How was this fixed in 4.1.42? I am having the same issue and still can not find a public constructor for BluetoothDeviceInfo which accepts a BluetoothAddress.

**Comment by peterfoot** [comment]
Sorry, a bit pre-emptive there. 42 contains the architectural change. 4.1.43 adds the address constructor.
