### ISSUE TITLE
Support BlueZ 5

### ISSUE THREAD

**Issue by peterfoot** [inthehand/32feet#37]
BlueZ 5 introduces changes to the API so will require code changes:-
http://www.bluez.org/bluez-5-api-introduction-and-porting-guide/

Opened as separate issue from #6

**Comment by werddomain** [comment]
is there any update about this?
Like .net core on linux?

**Comment by peterfoot** [comment]
Ideally I need some help adding new platforms. Please let me know if you'd like to contribute a Linux provider.

**Comment by werddomain** [comment]
When i find a way to use bluetooth on raspberry pi in c#, i will be able to help this project ...

**Comment by asheesh1996** [comment]
Are there any updates on this issue.

**Comment by DamianSuess** [comment]
@peterfoot thank you for supporting the [Linux.Bluetooth](https://github.com/SuessLabs/Linux.Bluetooth) project as part of 32feet!  It's truly an honor, as I started using your library 10+ years ago, and it inspired me to build this.

Please let me know if there are any API-level changes that would make support for your project easier. I'd be happy to work with you. 👍

**Comment by peterfoot** [comment]
Thanks, it provides a great API over the DBus workings. I didn't want to reinvent the wheel so am trying to incorporate it so it's another platform supported with the same cross-platform API (which itself is based on WebBluetooth). I've not had a lot of time to work on it so it's still a work in progress.

**Comment by peterfoot** [comment]
@DamianSuess if I recall, Linux.Bluetooth doesn't currently support Descriptors? At some point it would be useful to add those if they are not currently in progress...

**Comment by DamianSuess** [comment]
@peterfoot, I'll get it on the backlog and let's make it happen

**Comment by whSwitching** [comment]
#149  take me here,  any progress on this?
