### ISSUE TITLE
Simultaneous file transfers(OBEX)

### ISSUE THREAD

**Issue by tumelosbk** [inthehand/32feet#38]
Humble greetings.

A few years ago I built a c# app that copies the same file to multiple Bluetooth devices simultaneously using multi-threading. I am trying to recreate the same app, but with more features using newer technology(latest 32feet.net version and Visual Studio 2017)

I'm trying to recreate the project from scratch. But I keep getting an exception when I call "ObexWebResponse response = (ObexWebResponse)request.GetResponse();" that Only 1 use of the network/protocol/address can be used at a time.

So should I downgrade the library version? (If that's even possible) Or how can I get passed this issue?
Thanks for the help in advance

**Comment by peterfoot** [comment]
This can depend on the Bluetooth stack on the PC you are running on. Is this the Microsoft stack or other? This might be useful - https://github.com/inthehand/32feet/wiki/Stack-Identification
