### ISSUE TITLE
Incomming SerialPort

### ISSUE THREAD

**Issue by VervaekeSofie** [inthehand/32feet#386]
Is it possible to connect with a incomming SPP in Windows. So the Windowsprogram is waiting until a mobile device is connecting

**Comment by peterfoot** [comment]
Yes, using the BluetoothListener with the SerialPort service uuid allows you to create a listener that other devices can connect to. Some more information in the Wiki - https://github.com/inthehand/32feet/wiki/Bluetooth-Server-side
