### ISSUE TITLE
Platform not supported exception in Unity : 32feet.NET not supporting bluetooth stack 

### ISSUE THREAD

**Issue by rabhattaraiL** [inthehand/32feet#40]
I have been trying to connect to BioRadio device through bluetooth. My code works on visual studio and collects the required data after bluetooth connection. When I try to run it from Unity, it does not work and gives the exception error of 32feet.NET.  I did add the nuget package from the references tab in visual studio but it still shows the same error. I am new to Unity and using bluetooth through visual studio. 
Would anyone help to understand step by step how to resolve it ?

**Comment by PocketDoor** [comment]
I am also having issues with "PlatfornNotSupportedException" in a similar situation.

**Comment by jcs090218** [comment]
Any progress or solution on this?

**Comment by peterfoot** [comment]
Are you using the current InTheHand.Net.Bluetooth 4.0.6 release?

**Comment by jcs090218** [comment]
@peterfoot Who were you referring to? :)

I have not try this package yet, and I am just looking for possible development obstacle. I wonder if this problem are resolved because I am about to use this package with Unity and build to other platform! 😖 Thanks! 😄

**Comment by peterfoot** [comment]
There was actually a bug that was resolved in 4.0.8 to fix connection issues on Mono (inc Unity). All functionality should now be enabled inside Unity
