### ISSUE TITLE
support avalonia?

### ISSUE THREAD

**Issue by mingyangzhu** [inthehand/32feet#406]
hi , this great lib have plan to support Avalonia?

**Comment by peterfoot** [comment]
The library already supports Avalonia. You will need to implement your own way of requesting permissions where required as the InTheHand.Bluetooth.Permissions library is tied to Xamarin.Forms or .NET MAUI.

**Comment by mingyangzhu** [comment]
> The library already supports Avalonia. You will need to implement your own way of requesting permissions where required as the InTheHand.Bluetooth.Permissions library is tied to Xamarin.Forms or .NET MAUI.

tks for your reply ,this lib is very great.
