### ISSUE TITLE
How to determine if a bluetooth adapter is bluetooth 4.0 compatible

### ISSUE THREAD

**Issue by vpenades** [inthehand/32feet#42]
We're working with a device that requires bluetooth 4.0...  it's been given us connection problems until we realized the bluetooth radio is an old bluetooth 2.0 adapter.

Is there a way of knowing if a bluetooth adapter is 4.0?

In particular, I am interested in the LMP version.

Looking at the code, I've notice in the Win32 platform code, there's a _radioInfo structure that contains a lmpSubversion field... but where is the major version?

Could these values be exposed in the public API ?

from the LMP I can get the bluetooth version:

    LMP 9.x – Bluetooth 5.0
    LMP 8.x – Bluetooth 4.2
    LMP 7.x – Bluetooth 4.1
    LMP 6.x – Bluetooth 4.0
    LMP 5.x – Bluetooth 3.0 + HS
    LMP 4.x – Bluetooth 2.1 + EDR
    LMP 3.x – Bluetooth 2.0 + EDR
    LMP 2.x – Bluetooth 1.2
    LMP 1.x – Bluetooth 1.1
    LMP 0.x – Bluetooth 1.0b

thanks

**Comment by peterfoot** [comment]
BluetoothRadio.LmpVersion will expose this version
