### ISSUE TITLE
 BLE support

### ISSUE THREAD

**Issue by zs2388211949** [inthehand/32feet#47]
32feet  is a very good library, and i have  used this for many years, vv thanks.

but 32feet currently only supports  classic bluetooth.  NOW more and more BLE devices.  
so,  is plan to add BLE support?

**Comment by peterfoot** [comment]
Hi, I've been working on Bluetooth LE support and while it's not integrated into the main library I hope to reorganise the code soon. I'm reworking the current 32feet library with .NET Standard support with cross platform support for Windows, Android etc and the Bluetooth LE API will support iOS, Mac etc too.

**Comment by zs2388211949** [comment]
thanks for answering.  
very looking forward to...
