### ISSUE TITLE
Underlying socket not closed on win32

### ISSUE THREAD

**Issue by tvoyle** [inthehand/32feet#49]
When using InTheHand.Devices.Bluetooth on Windows 10  RfcommDeviceService.OpenStream does not create the NetworkStream with ownership of the Rfcomm socket. This means the socket is not closed when the stream is closed. At the moment I need to either use a wrapper class or call the socket Close method through reflection. I suspect this may apply to more than just the windows version.

**Comment by peterfoot** [comment]
Good catch. This may well change anyway and use the custom NetworkStream to work across .NET Framework (desktop) and Unity/Mono runtimes but there is certainly an opportunity for a quick fix in the mean time.
