### ISSUE TITLE
Is there a signed (strong named) version available in nuget ?

### ISSUE THREAD

**Issue by Karthik-Nagendiran** [inthehand/32feet#50]

**Comment by peterfoot** [comment]
Not currently. If there is enough interest for one I can consider adding it.

**Comment by DSelitskiy** [comment]
Yes, please. This is an issue I ran into when upgrading from 3.5 (32Feet.Net nuget) to latest

**Comment by h2oboi89** [comment]
Same issue.

**Comment by peterfoot** [comment]
Could you use this until a solution is available? - https://github.com/dsplaisted/strongnamer

**Comment by bacelar-eticadata** [comment]
Please relase 4.1 ASAP. I have the same problem...

**Comment by joaommvsoares** [comment]
Hello!
Could you anticipate this for version 4.0.9?

**Comment by peterfoot** [comment]
Resolved in 4.0.12

**Comment by bacelar-eticadata** [comment]
> 
> 
> Resolved in 4.0.12

Thank you!
