### ISSUE TITLE
Bluetooth LE support for Windows Form APP

### ISSUE THREAD

**Issue by Yongwei-Yao** [inthehand/32feet#55]
Hi，

I have an existing Windows Form C# application, and now this application needs to support connecting to Bluetooth LE devices.

 Currently, Is there the method to  support  discovery and connect Bluetooth LE device for Windows Form application on 32feet?

**Comment by peterfoot** [comment]
Currently 32feet only supports Bluetooth Classic (RFComm)

**Comment by peterfoot** [comment]
The InTheHand.BluetoothLE library (in preview on NuGet) supports Bluetooth Low Energy. The windows version supports Windows 10 either through UWP or desktop apps.
