### ISSUE TITLE
SelectBluetoothDeviceDialog can't be found gamepad?

### ISSUE THREAD

**Issue by lhappyb** [inthehand/32feet#57]
I use SelectBluetoothDeviceDialog properties in windows 10，but only discovery phone's bluetooth, but no gamepad device or other device.

is the SelectBluetoothDeviceDialog's limitation?

**Comment by peterfoot** [comment]
You can apply filters for specific device types but it should detect all Bluetooth Classic device types. XBox Controllers are a special case though.
