### ISSUE TITLE
Access to BLE classes

### ISSUE THREAD

**Issue by gberkheiser** [inthehand/32feet#58]
I'm working on a windows desktop application that needs to communicate with BLE devices.  For various reasons it can't be UWP.  I can see the BLE classes in the folder structure, but not in any of the csproj files.  This brings up a couple of questions.
1. What csproj should they be added into, assuming they don't get their own csproj?
2. What versions of Windows do these classes support?

Thanks.

**Comment by peterfoot** [comment]
The Bluetooth LE functionality is now in its own dedicated library - InTheHand.BluetoothLE which is on NuGet and inside a separate project in the source code. You can use the Windows APIs from .NET Framework desktop apps. A .NET Core build will be available shortly.
