### ISSUE TITLE
MONO compatibility

### ISSUE THREAD

**Issue by lordbarba** [inthehand/32feet#6]
Hi, 
Is it compatible with MONO and, maybe, with Raspberry PI 3 Bluetooth on board device?

Thanks
Leo

**Comment by Moulde** [comment]
I am interested in this as well.

**Comment by peterfoot** [comment]
There is some information here on the BlueZ support in the code (but not in the NuGet package). Definitely interested in making this easier and supporting Raspberry Pi and similar

**Comment by peterfoot** [comment]
Closing and tracking issue with #37
