### ISSUE TITLE
Not detecting Custom Built BLE ( UART/Serial Portal Type)

### ISSUE THREAD

**Issue by AnandThurubatla** [inthehand/32feet#60]
I have created WPF Application using this Library. It works fine on my laptop and detecting all nearby BLE Devices and able to pair up. But the same code failing to detect Custom built BLE Devices. Our Custom BLE device Firmware programmed based on https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/bluetooth/peripheral_uart/README.html

Kindly suggest solution.

**Comment by peterfoot** [comment]
InTheHand.BluetoothLE should be used for Bluetooth LE communications. It doesn't currently support pairing devices but you can get a list of devices currently paired on the system.
