### ISSUE TITLE
Can't send file to Canon Zeomini Bluetooth file

### ISSUE THREAD

**Issue by ifurkanvural** [inthehand/32feet#61]
Hello,

I can send file from PC to PC via blueetooth using this library. But same code is not working with bluetooth printer Canon Zeomini. 

Do you you have any ideo why is nor working ?

**Comment by peterfoot** [comment]
Do you know what profile the receiving device implements - it probably uses Object Push which requires specific formatting rather than just opening a connection and sending the file contents.
