### ISSUE TITLE
InTheHand.Devices.Bluetooth not contained in package nuget 

### ISSUE THREAD

**Issue by volostnovM** [inthehand/32feet#62]
I want to use the following code to work with Bluetooth LE:
`            var picker = new InTheHand.Devices.Enumeration.DevicePicker();
            var deviceInfo = picker.PickSingleDeviceAsync().GetAwaiter().GetResult();
            var bleDevice = InTheHand.Devices.Bluetooth.BluetoothLEDevice.FromDeviceInformationAsync(deviceInfo).GetAwaiter().GetResult();`
ut strangely, BluetoothLEDevice is not contained in the nTheget package TheTheand. Devices. Bluetooth for the .NET Framework 4.6.1. 
Although in the code for the desired platform it is [https://github.com/inthehand/32feet/blob/47e2762f044de950fda4add8597182bdad4a1f8f/InTheHand.Devices.Bluetooth/Platforms/win32/BluetoothLEDevice.Win32.cs](url)

**Comment by peterfoot** [comment]
The original InTheHand.Devices.Bluetooth is now obsolete. InTheHand.Net.Bluetooth contains Bluetooth Classic and InTheHand.BluetoothLE contains Bluetooth LE functionality and is in preview.
