### ISSUE TITLE
How to use 32feet to develop ble communication on Windows7?

### ISSUE THREAD

**Issue by LcFireRabbit** [inthehand/32feet#63]
32feet is a good library, I have used it to develop classic bluetooth, but now I am developing ble on Windows7, it seems that 32feet cannot support. A lot of people tell me that Windows7 cannot develop Ble, is it true?

**Comment by peterfoot** [comment]
Windows 7 has no built-in BTLE API. It may be possible using a third-party SDK but there isn't a standard approach. We will be releasing a Bluetooth LE library to complement the existing Bluetooth Classic one but it will only support the standard Windows 10 API on Windows.

**Comment by LcFireRabbit** [comment]
Thank you very much for your reply. It seems that I can only use serial communication.
