### ISSUE TITLE
relative path not found

### ISSUE THREAD

**Issue by mtyeager** [inthehand/32feet#64]
Sorry, probably a dumb question, but I loaded the solution into VS2019, and it is failing to build in part due to two references to IOBluetooth.framework and IOBluetoothUI.framework. Wondering what those are and how best to resolve. See picture.
![error](https://user-images.githubusercontent.com/42704355/72740369-88c34d80-3b73-11ea-8053-874797d81a30.png)

**Comment by peterfoot** [comment]
Thanks for spotting this, I will need to fix these to paths which work regardless of the project file location. The \System\Library\Frameworks folder should be present on all macs with XCode installed so should work as a fixed absolute path in this case.

**Comment by mtyeager** [comment]
Hi Peter,

I am working using VS on Windows 10. Was the intention that this be workable on Windows? Or only Mac?

Thanks,

Michael

**Comment by peterfoot** [comment]
The native macOS libraries should only build on a Mac. Temporarily you can exclude them from the build but I need to tweak the solution to work around this.

Peter

Sent from my phone
________________________________
