### ISSUE TITLE
No supported Bluetooth protocol stack found.

### ISSUE THREAD

**Issue by ThelemeGrand** [inthehand/32feet#71]
i use win7 and csr8510,
when i use "new BluetoothClient()", i get an error.
No supported Bluetooth protocol stack found.

**Comment by peterfoot** [comment]
Can you follow the instructions here to identify the installed stack:-
https://github.com/inthehand/32feet/wiki/Stack-Identification

The v4 release only supports the Microsoft stack. From Windows 7 the Broadcomm "stack" is an extension to the Microsoft stack and so this is also compatible.
