### ISSUE TITLE
[QUESTION] AVRCP remote control

### ISSUE THREAD

**Issue by steam3d** [inthehand/32feet#73]
Is it possible for 32feet to send and receive AVRCP commands?
I read wiki it says that L2CAP support only certain manufacturers.  It is not enough for me.

**Comment by peterfoot** [comment]
Currently the library supports only RFComm profiles across the board. OBEX profiles are supported because this sits upon RFComm.

**Comment by steam3d** [comment]
I'd like to clarify. I can't connect to  AVRCP via RFComm?
I tried but did not have success.

**Comment by peterfoot** [comment]
That’s correct, you can’t use an RFComm socket for this

**Comment by steam3d** [comment]
Thx,
