### ISSUE TITLE
Unable to install NuGet package InTheHand.Net.Bluetooth 4.0.5 into .NET Framework 4.8 project

### ISSUE THREAD

**Issue by Deilan** [inthehand/32feet#74]
Created a brand .NET Framework 4.8 Console App in Visual Studio 2019. Tried to install NuGet package InTheHand.Net.Bluetooth 4.0.5. Got an error:
`Package 'MSBuild.Sdk.Extras 2.0.54' has a package type 'MSBuildSdk' that is not supported by project 'ConsoleApp'.`

But 4.0.4 installs just fine, without any errors.

**Comment by soyxan** [comment]
Same here in Windows Forms application.

**Comment by peterfoot** [comment]
This is fixed in 4.0.6
