### ISSUE TITLE
[Question] Socket exception: The operation completed successfully.

### ISSUE THREAD

**Issue by jcs090218** [inthehand/32feet#76]
I am trying to connect to my raspberry pi device, yet no luck doing it. I am getting `Socket exception: The operation completed successfully.` message and I have no idea why is an error message saying something successfully? 😕 

Here is the code, what am I doing wrong? Thanks!

```cs
var cli = new BluetoothClient();
IReadOnlyCollection<BluetoothDeviceInfo> peers = cli.DiscoverDevices();

foreach (var bdi in peers)
{
    print(bdi.DeviceName);

    if (bdi.DeviceName == "raspberrypi")
        mDevice = bdi;
}

if (mDevice != null)
    print("Address: " + mDevice.DeviceAddress);

// Error here!
cli.Connect(mDevice.DeviceAddress, BluetoothService.SerialPort);

NetworkStream stream = cli.GetStream();
```

**Comment by jcs090218** [comment]
Okay, the same code works in normal C# application but not in Unity. :(

**Comment by peterfoot** [comment]
This should be resolved in 4.0.7 which was just published on NuGet

**Comment by jcs090218** [comment]
Thanks! I will try this when I have time! 😄

**Comment by jcs090218** [comment]
I have tested with version `4.0.8`! Thanks! 😄
