### ISSUE TITLE
Did i wrong?  Git clone and built samples.  i got some error 

### ISSUE THREAD

**Issue by MauryMa** [inthehand/32feet#79]
i can not find  GenericAttributeProfile in  nTheHand.Bluetooth.
what happend? it's sample that i  wanted to built.

**Comment by peterfoot** [comment]
Sorry, the samples require changes because of some naming changes in the library.

**Comment by MauryMa** [comment]
> Sorry, the samples require changes because of some naming changes in the library.

Doesn't matter

**Comment by MauryMa** [comment]
Hi Do you have any update

**Comment by peterfoot** [comment]
Are they still not working for you? The sample app has been rewritten

**Comment by MauryMa** [comment]
yes, thank you it was worked  for me. Sorry, Because of Oct1-8 was China Holiday So that i got some rested
