### ISSUE TITLE
Detect Bluetooth LE

### ISSUE THREAD

**Issue by etrbet** [inthehand/32feet#8]
Hi I develop windows form app with C# and I use 32feet api for bluetooh. I can get Bluetooth devices but I cant get Bluetooth LE devices. Is there any way to get BLE devices on 32feet ?

**Comment by peterfoot** [comment]
32feet currently only supports Bluetooth Classic. For Windows 8.1 and upwards you can call the WinRT/UWP API from a desktop app (Windows.Devices.Enumeration etc namespaces)

**Comment by mahmad123** [comment]
any plans to add BLE support?

**Comment by Deluril** [comment]
G'day. Would there happen to be any update on the introduction of support for Bluetooth LE into the 32feet libraries? I am currently working on a project that is utilising BLE modules and I need to integrate support for connecting to these into a pre-existing Windows Forms app.

**Comment by fuzioncode** [comment]
Any updates on this ?  Want to connect to BLE nRF device using .NET Core 2.2 and greater?

**Comment by peterfoot** [comment]
InTheHand.BluetoothLE (currently pre-release on NuGet) contains Bluetooth LE functionality. It's still part of 32feet.NET but separate from the Bluetooth Classic API
