### ISSUE TITLE
InTheHand.BluetoothLE (4.0.14-pre) - Bluetooth.ScanForDevicesAsync returns empty collection

### ISSUE THREAD

**Issue by juliokele** [inthehand/32feet#90]
Console App; TargetFramework: net462
```
var requestDeviceOptions = new RequestDeviceOptions
{
    AcceptAllDevices = true
};
var devices = await Bluetooth.ScanForDevicesAsync(requestDeviceOptions);
```

**Comment by peterfoot** [comment]
It's using the wrong selector and so not triggering a scan, fixing now

**Comment by juliokele** [comment]
It's working but very slow, elapsing aprox: 15s

**Comment by peterfoot** [comment]
I agree this is less than ideal. The solution to this is to change the implementation from the native FindAllAsync to use a DeviceWatcher and handle events as devices are encountered. I would have to consider this an enhancement for a future release rather than an urgent fix though.

**Comment by fantomen70** [comment]
I have the same problem with scanning on Android. 
Version 4.0.33.
