### ISSUE TITLE
The 32Feet.NET BLE works on Windows Form

### ISSUE THREAD

**Issue by Dhanabhon** [inthehand/32feet#95]
I would like to know the 32Feet.NET Bluetooth Low Energy (BLE) works on the Windows form app?

**Comment by peterfoot** [comment]
Yes, the InTheHand.BluetoothLE library supports desktop apps via either .NET 4.6.1 and above or .NET Core 3.1 and above. The PC must be running Windows 10 Build 18362 (1903) or later.

**Comment by Dhanabhon** [comment]
@peterfoot Thank you very much for your reply.
